# Generated by Django 2.2.2 on 2019-06-20 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 8, 15, 34, 714008, tzinfo=utc)),
        ),
    ]
