# Generated by Django 2.2.2 on 2019-06-24 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20190623_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 14, 6, 48, 953768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 14, 6, 48, 952860, tzinfo=utc)),
        ),
    ]
